name: Stream App Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy in EC2

    - name: Install dependencies
      run: |
        composer install -o
        npm
    - name: Build
      run: npm build
      
    - name: Sync
      env:
        dest: 'ubuntu@3.101.55.110:/home/material-server'
      run: |
        echo "${{secrets.AWS_PRIVATE_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        cd /home/material-stream &&
        git checkout main &&
        git fetch --all &&
        git reset --hard origin/main &&
        git pull origin main &&
        npm install
        pm2 restart 0
